export const KafkaEvents = Object.freeze({
  USER_REGISTERED:
    'USER_REGISTERED',

  USER_UPDATED:
    'USER_UPDATED',

  USER_DELETED:
    'USER_DELETED',

  USER_PASSWORD_CHANGED:
    'USER_PASSWORD_CHANGED',

  USER_PASSWORD_RESET_REQUESTED:
    'USER_PASSWORD_RESET_REQUESTED',

  USER_EMAIL_VERIFIED:
    'USER_EMAIL_VERIFIED',

  USER_PHONE_VERIFIED:
    'USER_PHONE_VERIFIED',
});